2018-09-14 14:16:29,582 ERROR: Exception on /reset_password_request [POST] [in /www/blog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/www/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/www/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/www/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/www/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/www/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/www/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/blog/app/routes.py", line 167, in reset_password_request
    send_password_reset_email(user)
  File "/www/blog/app/email.py", line 18, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2018-09-14 14:16:33,807 ERROR: Exception on /reset_password_request [POST] [in /www/blog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/www/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/www/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/www/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/www/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/www/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/www/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/blog/app/routes.py", line 167, in reset_password_request
    send_password_reset_email(user)
  File "/www/blog/app/email.py", line 18, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2018-09-14 14:16:46,764 ERROR: Exception on /reset_password_request [POST] [in /www/blog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/www/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/www/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/www/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/www/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/www/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/www/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/blog/app/routes.py", line 167, in reset_password_request
    send_password_reset_email(user)
  File "/www/blog/app/email.py", line 18, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2018-09-14 14:19:53,214 INFO: Microblog startup [in /www/blog/app/__init__.py:47]
2018-09-17 09:01:20,679 INFO: Microblog startup [in /www/blog/app/__init__.py:50]
2018-09-17 09:12:07,758 INFO: Microblog startup [in /www/blog/app/__init__.py:50]
2018-09-17 09:13:39,134 INFO: Microblog startup [in /www/blog/app/__init__.py:50]
2018-09-17 09:15:12,868 INFO: Microblog startup [in /www/blog/app/__init__.py:50]
2018-09-17 09:16:41,600 INFO: Microblog startup [in /www/blog/app/__init__.py:50]
2018-09-17 09:17:40,161 INFO: Microblog startup [in /www/blog/app/__init__.py:50]
2018-09-17 09:20:53,380 INFO: Microblog startup [in /www/blog/app/__init__.py:50]
2018-09-17 09:22:01,038 INFO: Microblog startup [in /www/blog/app/__init__.py:53]
